backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: product
    label: Product
    folder: src/content/products
    create: true
    fields:
      - { name: name, label: Name }
      - { name: image, label: Image }
      - { name: price, label: Price, valueType: int }
      - { name: id, label: ID }
      - { name: body, label: Description, widget: markdown }