backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: product
    label: Product
    folder: content/products
    create: true
    fields:
      - { name: name, label: Name }